version: '3.7'

services:
  redis:
    hostname: dev-redis
    container_name: dev-redis
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_EXTRA_FLAGS=--maxmemory 100mb
    networks:
      - localdev
    volumes:
      - redis-store:/bitnami/redis/data
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "1.0"

  cli:
    build:
      context: .
      dockerfile: docker/build/php/Dockerfile
    profiles: ['cli']
    container_name: php-cli
    init: true
    networks:
      - localdev
    working_dir: /app/
    volumes:
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/config/php/conf.d/extension.ini:/usr/local/etc/php/conf.d/extension.ini
      - ./docker/config/bash/bashrc-docker:/root/.bashrc
      - ./docker/config/bash/bash_history:/root/.bash_history
      - ./:/app/
    environment:
      - TERM=xterm-256color
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: /bin/bash

  clix:
    build:
      args:
        - XDEBUG_MODE=debug
      context: .
      dockerfile: docker/build/php/Dockerfile
    profiles: ['clix']
    container_name: php-clix
    init: true
    networks:
      - localdev
    working_dir: /app/
    volumes:
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/config/php/conf.d/extension.ini:/usr/local/etc/php/conf.d/extension.ini
      - ./docker/config/bash/bashrc-docker:/root/.bashrc
      - ./docker/config/bash/bash_history:/root/.bash_history
      - ./:/app/
    environment:
      - TERM=xterm-256color
      - XDEBUG_MODE=debug
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: /bin/bash
    expose:
      - 9000
      - 9003

volumes:
  redis-store:
    driver: local

networks:
  localdev:
    driver: bridge
