<?php declare(strict_types = 1);

namespace Everon\Logger\Configurator\Plugin;

use Everon\Logger\Configurator\AbstractArrayableConfigurator;
use InvalidArgumentException;
use UnexpectedValueException;
use function array_key_exists;
use function ctype_upper;
use function is_array;
use function is_object;
use function method_exists;
use function sprintf;
use function strtolower;
use function trim;

/**
 * Code generated by POPO generator, do not edit.
 * https://packagist.org/packages/popo/generator
 */
class RedisConnectionConfigurator extends AbstractArrayableConfigurator
{
    protected array $data = [
        'host' => null,
        'port' => 6379,
        'timeout' => 0.0,
        'password' => null,
        'persistentId' => null,
        'retryInterval' => 0,
        'readTimeout' => 0.0,
    ];

    protected array $default = [
        'host' => null,
        'port' => 6379,
        'timeout' => 0.0,
        'password' => null,
        'persistentId' => null,
        'retryInterval' => 0,
        'readTimeout' => 0.0,
    ];

    protected array $propertyMapping = [
        'host' => 'string',
        'port' => 'int',
        'timeout' => 'float',
        'password' => 'string',
        'persistentId' => 'string',
        'retryInterval' => 'int',
        'readTimeout' => 'float',
    ];

    protected array $collectionItems = [
    ];

    protected array $updateMap = [];

    public function toArray(): array
    {
        $data = [];

        foreach ($this->propertyMapping as $key => $type) {
            if (!array_key_exists($key, $data)) {
                $data[$key] = $this->default[$key] ?? null;
            }
            $value = $this->data[$key];

            if ($this->isCollectionItem($key) && is_array($value)) {
                foreach ($value as $popo) {
                    if (is_object($popo) && method_exists($popo, 'toArray')) {
                        $data[$key][] = $popo->toArray();
                    }
                }

                continue;
            }

            if (is_object($value) && method_exists($value, 'toArray')) {
                $data[$key] = $value->toArray();
                continue;
            }

            $data[$key] = $value;
        }

        return $data;
    }

    protected function isCollectionItem(string $key): bool
    {
        return array_key_exists($key, $this->collectionItems);
    }

    public function fromArray(array $data): RedisConnectionConfigurator
    {
        foreach ($this->propertyMapping as $key => $type) {
            $result[$key] = $this->default[$key] ?? null;

            if ($this->typeIsObject($type)) {
                $popo = new $this->propertyMapping[$key];
                if (method_exists($popo, 'fromArray')) {
                    $popoData = $data[$key] ?? $this->default[$key] ?? [];
                    $popo->fromArray($popoData);
                }
                $result[$key] = $popo;

                continue;
            }

            if (array_key_exists($key, $data)) {
                if ($this->isCollectionItem($key)) {
                    foreach ($data[$key] as $popoData) {
                        $popo = new $this->collectionItems[$key]();
                        if (method_exists($popo, 'fromArray')) {
                            $popo->fromArray($popoData);
                        }
                        $result[$key][] = $popo;
                    }
                }
                else {
                    $result[$key] = $data[$key];
                }
            }
        }

        $this->data = $result;

        foreach ($data as $key => $value) {
            if (!array_key_exists($key, $result)) {
                continue;
            }

            $type = $this->propertyMapping[$key] ?? null;
            if ($type !== null) {
                $value = $this->typecastValue($type, $result[$key]);
                $this->popoSetValue($key, $value);
            }
        }

        return $this;
    }

    /**
     * @param string $type
     * @param mixed $value
     *
     * @return mixed
     */
    protected function typecastValue(string $type, $value)
    {
        if ($value === null) {
            return $value;
        }

        switch ($type) {
            case 'int':
                $value = (int) $value;
                break;
            case 'string':
                $value = (string) $value;
                break;
            case 'bool':
                $value = (bool) $value;
                break;
            case 'array':
                $value = (array) $value;
                break;
        }

        return $value;
    }

    public function isNew(): bool
    {
        return empty($this->updateMap);
    }

    /**
     * @return string|null
     */
    public function getHost(): ?string
    {
        return $this->popoGetValue('host');
    }

    /**
     * @param string|null $host
     *
     * @return RedisConnectionConfigurator
     */
    public function setHost(?string $host): RedisConnectionConfigurator
    {
        $this->popoSetValue('host', $host);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return string
     * @throws \UnexpectedValueException
     *
     */
    public function requireHost(): string
    {
        $this->assertPropertyValue('host');

        return (string) $this->popoGetValue('host');
    }

    /**
     * @param string $property
     *
     * @return void
     * @throws UnexpectedValueException
     */
    protected function assertPropertyValue(string $property): void
    {
        if (!isset($this->data[$property])) {
            throw new UnexpectedValueException(sprintf(
                'Required value of "%s" has not been set',
                $property
            ));
        }
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasHost(): bool
    {
        return $this->updateMap['host'] ?? false;
    }

    /**
     * @return integer|null
     */
    public function getPort(): ?int
    {
        return $this->popoGetValue('port');
    }

    /**
     * @param integer|null $port
     *
     * @return RedisConnectionConfigurator
     */
    public function setPort(?int $port): RedisConnectionConfigurator
    {
        $this->popoSetValue('port', $port);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return integer
     * @throws \UnexpectedValueException
     *
     */
    public function requirePort(): int
    {
        $this->assertPropertyValue('port');

        return (int) $this->popoGetValue('port');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasPort(): bool
    {
        return $this->updateMap['port'] ?? false;
    }

    /**
     * @return float|null
     */
    public function getTimeout(): ?float
    {
        return $this->popoGetValue('timeout');
    }

    /**
     * @param float|null $timeout
     *
     * @return RedisConnectionConfigurator
     */
    public function setTimeout(?float $timeout): RedisConnectionConfigurator
    {
        $this->popoSetValue('timeout', $timeout);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return float
     * @throws \UnexpectedValueException
     *
     */
    public function requireTimeout(): float
    {
        $this->assertPropertyValue('timeout');

        return (float) $this->popoGetValue('timeout');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasTimeout(): bool
    {
        return $this->updateMap['timeout'] ?? false;
    }

    /**
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->popoGetValue('password');
    }

    /**
     * @param string|null $password
     *
     * @return RedisConnectionConfigurator
     */
    public function setPassword(?string $password): RedisConnectionConfigurator
    {
        $this->popoSetValue('password', $password);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return string
     * @throws \UnexpectedValueException
     *
     */
    public function requirePassword(): string
    {
        $this->assertPropertyValue('password');

        return (string) $this->popoGetValue('password');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasPassword(): bool
    {
        return $this->updateMap['password'] ?? false;
    }

    /**
     * @return string|null
     */
    public function getPersistentId(): ?string
    {
        return $this->popoGetValue('persistentId');
    }

    /**
     * @param string|null $persistentId
     *
     * @return RedisConnectionConfigurator
     */
    public function setPersistentId(?string $persistentId): RedisConnectionConfigurator
    {
        $this->popoSetValue('persistentId', $persistentId);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return string
     * @throws \UnexpectedValueException
     *
     */
    public function requirePersistentId(): string
    {
        $this->assertPropertyValue('persistentId');

        return (string) $this->popoGetValue('persistentId');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasPersistentId(): bool
    {
        return $this->updateMap['persistentId'] ?? false;
    }

    /**
     * @return integer|null
     */
    public function getRetryInterval(): ?int
    {
        return $this->popoGetValue('retryInterval');
    }

    /**
     * @param integer|null $retryInterval
     *
     * @return RedisConnectionConfigurator
     */
    public function setRetryInterval(?int $retryInterval): RedisConnectionConfigurator
    {
        $this->popoSetValue('retryInterval', $retryInterval);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return integer
     * @throws \UnexpectedValueException
     *
     */
    public function requireRetryInterval(): int
    {
        $this->assertPropertyValue('retryInterval');

        return (int) $this->popoGetValue('retryInterval');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasRetryInterval(): bool
    {
        return $this->updateMap['retryInterval'] ?? false;
    }

    /**
     * @return float|null
     */
    public function getReadTimeout(): ?float
    {
        return $this->popoGetValue('readTimeout');
    }

    /**
     * @param float|null $readTimeout
     *
     * @return RedisConnectionConfigurator
     */
    public function setReadTimeout(?float $readTimeout): RedisConnectionConfigurator
    {
        $this->popoSetValue('readTimeout', $readTimeout);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return float
     * @throws \UnexpectedValueException
     *
     */
    public function requireReadTimeout(): float
    {
        $this->assertPropertyValue('readTimeout');

        return (float) $this->popoGetValue('readTimeout');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasReadTimeout(): bool
    {
        return $this->updateMap['readTimeout'] ?? false;
    }

    /**
     * @param string $propertyName
     * @param mixed $value
     *
     * @return void
     * @throws \InvalidArgumentException
     */
    protected function addCollectionItem(string $propertyName, $value): void
    {
        $type = trim(strtolower($this->propertyMapping[$propertyName]));
        $collection = $this->popoGetValue($propertyName) ?? [];

        if (!is_array($collection) || $type !== 'array') {
            throw new InvalidArgumentException('Cannot add item to non array type: ' . $propertyName);
        }

        $collection[] = $value;

        $this->popoSetValue($propertyName, $collection);
    }

    /**
     * @param string $property
     *
     * @return mixed|null
     */
    protected function popoGetValue(string $property)
    {
        if (!isset($this->data[$property])) {
            if ($this->typeIsObject($this->propertyMapping[$property])) {
                $popo = new $this->propertyMapping[$property];
                $this->data[$property] = $popo;
            }
            else {
                return null;
            }
        }

        return $this->data[$property];
    }

    protected function typeIsObject(string $value): bool
    {
        return $value[0] === '\\' && ctype_upper($value[1]);
    }

    /**
     * @param string $property
     * @param mixed $value
     *
     * @return void
     */
    protected function popoSetValue(string $property, $value): void
    {
        $this->data[$property] = $value;

        $this->updateMap[$property] = true;
    }
}
